create table testcases_non_btree (
	id                  uuid primary key unique not null,
	problem_title       varchar references problems(title) not null,
	int_2d_array        bigint[][],
	int_2d_array2       bigint[][],
	float_2d_array      double precision[][],
	float_2d_array2     double precision[][],
	string_2d_array     varchar[][],
	string_2d_array2    varchar[][],
	byte_2d_array       bytea[][],
	byte_2d_array2      bytea[][],
	bool_2d_array       boolean[][],
	bool_2d_array2      boolean[][],
	int_array           bigint[],
	int_array2          bigint[],
	float_array         double precision[],
	float_array2        double precision[],
	string_array        varchar[],
	string_array2       varchar[],
	byte_array          bytea[],
	byte_array2         bytea[],
	bool_array          boolean[],
	bool_array2         boolean[],
	int_val             bigint,
	float_val           double precision,
	float_val2          double precision,
	int_val2            bigint,
	string_val          varchar,
	string_val2         varchar,
	byte_val            bytea,
	byte_val2           bytea,
	bool_val            boolean,
	bool_val2           boolean,
    created_at 			timestamp default now() not null,
    updated_at 			timestamp,
    deleted_at 			timestamp
);
